# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playWindow.ui'
#
# Created: Sun Dec 28 18:40:42 2014
# by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlayWindow(object):
    def setupUi(self, PlayWindow):
        PlayWindow.setObjectName(_fromUtf8("PlayWindow"))
        PlayWindow.resize(818, 600)
        self.centralwidget = QtGui.QWidget(PlayWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.homeButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.homeButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(40, 40))
        self.homeButton.setObjectName(_fromUtf8("homeButton"))
        self.horizontalLayout_3.addWidget(self.homeButton)
        self.profileLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.profileLabel.setFont(font)
        self.profileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.profileLabel.setObjectName(_fromUtf8("profileLabel"))
        self.horizontalLayout_3.addWidget(self.profileLabel)
        self.difficultyLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.difficultyLabel.setFont(font)
        self.difficultyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.difficultyLabel.setObjectName(_fromUtf8("difficultyLabel"))
        self.horizontalLayout_3.addWidget(self.difficultyLabel)
        self.timeLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeLabel.setFont(font)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.horizontalLayout_3.addWidget(self.timeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.scoreLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setObjectName(_fromUtf8("scoreLabel"))
        self.horizontalLayout.addWidget(self.scoreLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.scrambledLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrambledLabel.sizePolicy().hasHeightForWidth())
        self.scrambledLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.scrambledLabel.setFont(font)
        self.scrambledLabel.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.scrambledLabel.setObjectName(_fromUtf8("scrambledLabel"))
        self.horizontalLayout_4.addWidget(self.scrambledLabel, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.repeatButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.repeatButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.repeatButton.setIcon(icon1)
        self.repeatButton.setIconSize(QtCore.QSize(40, 40))
        self.repeatButton.setObjectName(_fromUtf8("repeatButton"))
        self.horizontalLayout_6.addWidget(self.repeatButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.nextButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("arrow_left_4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon2)
        self.nextButton.setIconSize(QtCore.QSize(40, 40))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout_6.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.resultLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName(_fromUtf8("resultLabel"))
        self.horizontalLayout_2.addWidget(self.resultLabel)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.checkButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.checkButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("right-wrong.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkButton.setIcon(icon3)
        self.checkButton.setIconSize(QtCore.QSize(50, 50))
        self.checkButton.setObjectName(_fromUtf8("checkButton"))
        self.horizontalLayout_2.addWidget(self.checkButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        PlayWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PlayWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        PlayWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PlayWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PlayWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlayWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayWindow)
        PlayWindow.setTabOrder(self.lineEdit, self.homeButton)
        PlayWindow.setTabOrder(self.homeButton, self.repeatButton)
        PlayWindow.setTabOrder(self.repeatButton, self.nextButton)
        PlayWindow.setTabOrder(self.nextButton, self.checkButton)

    def retranslateUi(self, PlayWindow):
        PlayWindow.setWindowTitle(_translate("PlayWindow", "Unscramblify", None))
        self.homeButton.setText(_translate("PlayWindow", "&Home Screen", None))
        self.profileLabel.setText(_translate("PlayWindow", "TextLabel", None))
        self.difficultyLabel.setText(_translate("PlayWindow", "TextLabel", None))
        self.timeLabel.setText(_translate("PlayWindow", "TextLabel", None))
        self.scoreLabel.setText(_translate("PlayWindow", "Score : ", None))
        self.scrambledLabel.setText(_translate("PlayWindow", "TextLabel", None))
        self.repeatButton.setText(_translate("PlayWindow", "&Repeat", None))
        self.nextButton.setText(_translate("PlayWindow", "&Next", None))
        self.resultLabel.setText(_translate("PlayWindow", "TextLabel", None))
        self.checkButton.setText(_translate("PlayWindow", "&Check Answer", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PlayWindow = QtGui.QMainWindow()
    ui = Ui_PlayWindow()
    ui.setupUi(PlayWindow)
    PlayWindow.show()
    sys.exit(app.exec_())

